name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v4 # Adds a step to checkout the repository code

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Build C#
      run: dotnet build

    - name: Test C#
      run: dotnet test

    - uses: actions/setup-node@v4
      with:
        node-version: '24.x'

    - name: Install npm packages
      working-directory: DotnetTemplate.Web
      run: npm install

    - name: Build TypeScript
      working-directory: DotnetTemplate.Web
      run: npm run build

    - name: Lint TypeScript
      working-directory: DotnetTemplate.Web
      run: npm run lint

    - name: Test TypeScript
      working-directory: DotnetTemplate.Web
      run: npm t
